In [2]:
import numpy as np 
a1=np.array([[1,2,3],[1,2,3]])
a2=np.array([1,2,3])
mul=a1*a2
       #or 
print("multiplication is a1 and a2:-",mul)
mul,"multiplication "

multiplication is a1 and a2:- [[1 4 9]
 [1 4 9]]


(array([[1, 4, 9],
        [1, 4, 9]]),
 'multiplication ')

In [20]:
v1=np.array([0,9,8])
v2=np.array([1,2,3])
print("mult",np.multiply(v1,v2))
"multiply:-",np.multiply(v1,v2)

mult [ 0 18 24]


('multiply:-', array([ 0, 18, 24]))

#Cross product of 2 vectors:-

In [22]:
v1=np.array([1,2,3])
v2=np.array([1,2,3])
print(   )                                #Using fun of cross !
print(np.cross(v1,v2))
np.cross(v1,v2)


[0 0 0]


array([0, 0, 0])

determinant of 2 array|

In [5]:
a1=np.array([[1,4],[4,6]])
a1=np.array([[1,3],[2,5]])    #Syntex to find determinant(np.linalg.det().   )
print("Determinant of this given a1 sq matrix is =",np.linalg.det(a1))    #Deter takes only one arguments not two!


Determinant of this given a1 sq matrix is = -1.0


Evaluate ensteins summation convention of tow multidiemintional array 

In [10]:
a1=np.array([[1,4],[2,3]])
a2=np.array([[6,3],[3,5]])
p=np.einsum(a1,a2)
print("ensteins summation con :-",p)     #np.einsum(a1,a2)

ValueError: must provide at least an operand and a subscripts list to einsum

In [14]:
a1=np.array([0,4,2,3,3])
a2=np.array([0,3,4,2,0])    #Inner product == #this sum of accto  axis =0 add all values 
im=np.inner(a1,a2)
im

26

In [45]:
import numpy as np

# Create two 1-D arrays 'a' and 'b'
a = np.array([1, 2, 5])
b = np.array([2, 1, 0])                  #I dont under stand this code 

# Display the original 1-D arrays 'a' and 'b'
print("Original 1-d arrays:")
print(a)
print(b)

# Calculate the inner product of arrays 'a' and 'b' using np.inner()
result = np.inner(a, b)

# Display the inner product of the said vectors
print("Inner product of the said vectors:")
print(result)

Original 1-d arrays:
[1 2 5]
[2 1 0]
Inner product of the said vectors:
4


In [21]:
p1=np.array([[1,2],[2,3]])
p2=np.array([[4,5],[2,1]])    #Kronker product 
print(np.kron(p1,p2))

[[ 4  5  8 10]
 [ 2  1  4  2]
 [ 8 10 12 15]
 [ 4  2  6  3]]


In [8]:
from numpy import linalg as LA
p1=np.array([[1,2],[2,3]])            #Vectors and matrix norms form 
print(LA.cond(p1))

17.944271909999173


In [7]:
p3=np.array([[1,2],[3,4]])
print(np.linalg.norm(p3))

5.477225575051661


In [11]:
p4=np.matrix('1,2;3,4')
print("matrix in norms:-",np.linalg.norm(p4))


matrix in norms:- 5.477225575051661


In [12]:
print(np.det(p4))

AttributeError: module 'numpy' has no attribute 'det'

In [14]:
print("Determinant :-",np.linalg.det(p4))

Determinant :- -2.0000000000000004
