#AIRTHMATICS OPERATION:-

In [3]:
import numpy as np 
# * multiply
# **  power
# /  divide 
# %  modulus (reminder)
# 1/a  reciprocal


In [5]:
a=np.array([4,6,2])
b=np.array([4,6,2])
print("sum:- ", a+b)

sum:-  [2 4 6]


In [16]:
#Same as python function 
print("multiply:-", a*b)
print("divide:-",a/b)
print("reminder:-",a%b)
print("reciprocal:-",1/a,1/b)
print("power",a**2)
print(a/2+b/2)

multiply:- [1 4 9]
divide:- [1. 1. 1.]
reminder:- [0 0 0]
reciprocal:- [1.         0.5        0.33333333] [1.         0.5        0.33333333]
power [1 4 9]
[1. 2. 3.]


#opperation function mathsmatics 


In [22]:
s=np.array([0,9,8])
d=np.array([0,9,8])
print("addition is:-",np.add(s,d) ,"or same method:-",np.array([0,9,8])+np.array([0,9,8]))    #add fun is imp for adding two numbers:-
print("not addition:-",sum(s,d))     # i don't know about this function 

addition is:- [ 0 18 16] or same method:- [ 0 18 16]
not addition:- [17 26 25]


In [31]:
print("mult",np.multiply(s,d))
print("div:-",np.divide(s,d))
#print("power:-",np.power(s,d))
print("reci:-",np.reciprocal(s,d))
print("rem:-",np.mod(s,d))


mult [0 0 0]
div:- [-0. inf inf]
reci:- [-2147483648           0           0]
rem:- [0 0 0]


C:\Users\DUSHYANT\AppData\Local\Temp\ipykernel_21952\881225770.py:2: RuntimeWarning: divide by zero encountered in divide
  print("div:-",np.divide(s,d))
C:\Users\DUSHYANT\AppData\Local\Temp\ipykernel_21952\881225770.py:4: RuntimeWarning: divide by zero encountered in reciprocal
  print("reci:-",np.reciprocal(s,d))
C:\Users\DUSHYANT\AppData\Local\Temp\ipykernel_21952\881225770.py:4: RuntimeWarning: invalid value encountered in reciprocal
  print("reci:-",np.reciprocal(s,d))
C:\Users\DUSHYANT\AppData\Local\Temp\ipykernel_21952\881225770.py:5: RuntimeWarning: divide by zero encountered in remainder
  print("rem:-",np.mod(s,d))


#for n dimentionalarray


In [51]:
q=np.array([[1,2,3],[1,2,3]]) 
print(q,q.dtype)
#only takes one or    #upper all functions is applycable:-

[[1 2 3]
 [1 2 3]] int32


In [52]:
q=np.array([[1,2,3],[1,2,3]],q.dtype)     #dtype  is notshowing datatype in np.array when you make a array!
print(q)
#only takes one in np.array, #upper all functions is applycable:-

[[1 2 3]
 [1 2 3]]


In [58]:
f=np.array([[[1,2],[3,4]]])
p=np.array([[1,2],[1,2]])
print(f.dtype,p.dtype)
print("sum is:-",np.add(f,p))
print("multiply:-",np.multiply(f,p))

int32 int32
sum is:- [[[2 4]
  [4 6]]]
[[[1 4]
  [3 8]]]


In [64]:
k=np.array([1,4,8,50,54])                      ##same as python function 
print(max(k)," or same as :-" ,np.max(k),min(k),np.min(k))


54  or same as :- 54 1 1


In [77]:
print(np.sqrt(k))                #ONLY THOSE FUNCTION IS RUN only np.
print(np.sin(k),"or",np.sin(1/2))
print(np.cos(k))
print("index no of min value:-",np.argmin(k),"index no of max value:-",np.argmax(k))
print(np.cumsum(k))      #sum deata hai ek kai bad ek ko jood detai hai exp:-[1,2,4,3]--->1+2,3+3,6+4so on.....

[1.         2.         2.82842712 7.07106781 7.34846923]
[ 0.84147098 -0.7568025   0.98935825 -0.26237485 -0.55878905] or 0.479425538604203
[ 0.54030231 -0.65364362 -0.14550003  0.96496603 -0.82930983]
index no of min value:- 0 index no of max value:- 4
[  1   5  13  63 117]


In [76]:
#axis 0=column
#axis 1=row          #not uderstand!
w=np.array([[1,4,3],[9,5,7,]])
print(np.argmin(w,axis=0))     

[0 0 0]


In [75]:
#axis 0=column
#axis 1=row
w=np.array([[1,4,3],[9,5,7,]])
print(np.min(w,axis=0))

[1 4 3]


#shape of numpy 


In [79]:
print(np.shape(k),np.shape(w))   #give dimention row and column

(5,) (2, 3)


In [80]:
l=np.array([[[[[1,2,3,45,6,9]]]]])     #give no of column and element
print(np.shape(l))                      

(1, 1, 1, 1, 7)


In [86]:
x=np.array([[[1,2,3],[5,6,4.2]]])
print(np.shape(x),x.shape ,"both of same method ")

(1, 2, 3) (1, 2, 3) both of same method 


#reshape any array 

In [96]:
#print(np.reshape(l)) #not because halfe information 
c=np.array([1,2,3,4,5,6])
print(c.reshape(2,3),"both same fujnction ",c.reshape(3,2))            # ×         

[[1 2 3]
 [4 5 6]] both same [[1 2]
 [3 4]
 [5 6]]


In [101]:
#for multidim array into 1D array 
aak=np.array([[[2,3],[3,4],[4,5]]])
print("orignal Array:-",aak)
print()
print("Reshaped array",np.shape(aak),aak.shape,aak.reshape(-1))

orignal Array:- [[[2 3]
  [3 4]
  [4 5]]]

Reshaped array (1, 3, 2) (1, 3, 2) [2 3 3 4 4 5]
