In [2]:
import numpy as np 
ar=np.array([1,2,3,4,5])
l=len(ar)
for i in range(l):
 print(i)

0
1
2
3
4


In [4]:
for i in range(5):
    print(ar[i])
    

1
2
3
4
5


In [23]:
sd=np.array([[1,2],[3,4]])
for j in sd:
  for g in j:          #Range depend on dimention of array prpostional to dimen!
      print(g)
    

1
2
3
4


In [27]:
#for example of 3d array 
d=np.array([[[1,2],[3,4]]])
print(d.ndim)
for i in d:
    for k in i:      #3d array make 3 loops 
        for s in k:
            print(s)

3
1
2
3
4


In [30]:
#SHORT METHOD for continous loop
for i in np.nditer(d):
    print(i)

1
2
3
4


scilicing with indexing no:-

In [7]:
d=np.array([1,2,3,4])        #give index no with value:-
for k,f in np.ndenumerate(d):
 print(k,f)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [11]:
kp=np.array([[[2,3],[1,4],[3,4]]])
for j,g in np.ndenumerate(kp):
    print(j,g)
    

(0, 0, 0) 2
(0, 0, 1) 3
(0, 1, 0) 1
(0, 1, 1) 4
(0, 2, 0) 3
(0, 2, 1) 4


#copy Vs view function:-


In [22]:
"""#copy:- copy function has own data memory 
#copy array is a new array 
#dont change data iterlinkig data 
if you copy the data then dont change data of copy """

cp=np.array([[2,6],[4,1]])
f=np.copy(cp)
cp[0,1]=99
print("orignal; data:-",cp)
print("copy data :-",f)
print("------->, same as method ")
print(np.copy(cp))
for w,v in np.ndenumerate(cp):
    print(w,v)   #for finding indexing! and taking return value


orignal; data:- [[ 2 99]
 [ 4  1]]
copy data :- [[2 6]
 [4 1]]
------->, same as method 
[[ 2 99]
 [ 4  1]]
(0, 0) 2
(0, 1) 99
(1, 0) 4
(1, 1) 1


In [37]:
cp=np.array([[2,6],[4,1]])
f=np.copy(cp)
cp[0,1]=99
print("orignal; data:-",cp)
print("copy data :-",f)
print("------->, same as method ")
print(cp.copy)
for w,v in np.ndenumerate(cp):
    print(w,v)   #for finding indexing! and taking return value


orignal; data:- [[ 2 99]
 [ 4  1]]
copy data :- [[2 6]
 [4 1]]
------->, same as method 
<built-in method copy of numpy.ndarray object at 0x0000029FCA7E7B10>
(0, 0) 2
(0, 1) 99
(1, 0) 4
(1, 1) 1


In [23]:
#But if we put change indexing no before copy data Then change both data simuntanausely:-  Example

cp=np.array([[2,6],[4,1]])
cp[0,1]=77
f=np.copy(cp)
print("orignal; data:-",cp)
print("copy data :-",f)
print("------->, same as method ")
print(np.copy(cp))
for w,v in np.ndenumerate(cp):
    print(w,v)   #for finding indexing! Both data changes copy and orignal data 


orignal; data:- [[ 2 77]
 [ 4  1]]
copy data :- [[ 2 77]
 [ 4  1]]
------->, same as method 
[[ 2 77]
 [ 4  1]]
(0, 0) 2
(0, 1) 77
(1, 0) 4
(1, 1) 1


#VIEW function:-

In [35]:
vi=np.array([[[9,6],[6,5]]])
#k=np.view(vi)
#print(k)
#print(np.view(vi))     #this method is not  correct!
b=vi.view
print(b)


<built-in method view of numpy.ndarray object at 0x0000016C43B07510>


In [31]:
vi=np.array([[[9,6],[6,8]]])
print(vi.view)
for k,i in np.ndenumerate(vi):
    print("index no:-",k,i)
vi[0,1,0]=55
print("orignal data:-",vi)
print("------>")
print("view data:-",vi)


<built-in method view of numpy.ndarray object at 0x0000029FCA711E90>
index no:- (0, 0, 0) 9
index no:- (0, 0, 1) 6
index no:- (0, 1, 0) 6
index no:- (0, 1, 1) 8
orignal data:- [[[ 9  6]
  [55  8]]]
------>
view data:- [[[ 9  6]
  [55  8]]]


In [32]:
vi=np.array([[[9,6],[6,8]]])
vi[0,1,0]=88      #Both data change as previous data! 
print(vi.view)
for k,i in np.ndenumerate(vi):
    print("index no:-",k,i)
print("orignal data:-",vi)
print("------>")
print("view data:-",vi)


<built-in method view of numpy.ndarray object at 0x0000029FCA7E77B0>
index no:- (0, 0, 0) 9
index no:- (0, 0, 1) 6
index no:- (0, 1, 0) 88
index no:- (0, 1, 1) 8
orignal data:- [[[ 9  6]
  [88  8]]]
------>
view data:- [[[ 9  6]
  [88  8]]]


#JOINIG ARRAY :-

In [30]:
#elements must be same for both numpy array 
ar=np.array([[[7,3],[6,0]]])
ar2=np.array([[[5,7],[8,3]]])
l=np.array([1,2,3,4])
p=np.array([1,2,3,4])
con=np.concatenate((l,p))     #NOTE this function  is work only 1 d array without passing indexing (list type)! it when works only when you does not pass axis 
print("new connect array without passing axis:-",con)

print("method 2:----> ")
con2=np.concatenate((ar,ar2),axis=1)
print(  )
print("new con array2 axis=1",con2)
con3=np.concatenate((l,p),axis=0)
print("concatenate about axis=0:-",con3)


new connect array without passing axis:- [1 2 3 4 1 2 3 4]
method 2:----> 

new con array2 axis=1 [[[7 3]
  [6 0]
  [5 7]
  [8 3]]]
concatenate about axis=0:- [1 2 3 4 1 2 3 4]


#STACK FUNCT CONCATENATE OF STRING!

In [46]:
l=np.array([1,2,3,4])
p=np.array([1,2,3,4])
stac=np.stack((l,p),axis=1)
print("simple stack data about axis=1,", stac)

stack=np.hstack((l,p))     #stack along row (length)
print("stack data about Row:-",stack )
print(    )

q=np.vstack((l,p))    #about column(breath)
print("along breath(column):-",q)
print(   )

print(np.dstack((l,p)),":-Along Height!")    #Along height

simple stack data about axis=1, [[1 1]
 [2 2]
 [3 3]
 [4 4]]
stack data about Row:- [1 2 3 4 1 2 3 4]

along breath(column):- [[1 2 3 4]
 [1 2 3 4]]

[[[1 1]
  [2 2]
  [3 3]
  [4 4]]] :-Along Height!


#SPLIT ARRAY INTO MANY ARARY:-

In [65]:
sp=np.array([1,2,3,4,5,6,7,8])
sp3=np.array([[1,2,3,4,5,6,7,8]])
sp2=np.array([[[4,4],[4,4],[5,5],[5,5]]])        #Array splite in combination of array,in dictionary !
split=np.split(sp,4)
print("split array:-", split)
print(  )

print("split 8 arrays:-",np.split(sp,8))
print()

print("3d array spliyte:-",split)
print(   )

print("splite along axis=1:-",np.split(sp3,4,axis=1))       
print( )
print("splite along axis=0:-",np.split(sp,4,axis=0))      

split array:- [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

split 8 arrays:- [array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8])]

3d array spliyte:- [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

splite along axis=1:- [array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]

splite along axis=0:- [array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


#Search (index no.)

In [82]:
s=np.array([3,2,5,3,6,3,4,5,8,2,4,4])
s2=np.array(["e","r","t","yu","u","d","yt","e","e",3,5,6])
j=np.where(s==3)
print(j)   #give index no
print(  )
print(np.where((s/2)==0))
print(  )
print(np.where("e"))
print(  )
print(np.searchsorted(s,9999),"index no!")      #You set  give 9999 index no!
print("find index no by side wise! ---->  ")
print(np.searchsorted(s,5,side="left"))
print("---->")
print(np.searchsorted(s,[6,7,5],side="left"))

(array([0, 3, 5], dtype=int64),)

(array([], dtype=int64),)

(array([0], dtype=int64),)

12 index no!
find index no by side wise! ---->  
12
---->
[12 12 12]


C:\Users\DUSHYANT\AppData\Local\Temp\ipykernel_8752\3764993888.py:8: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(arr).nonzero()` if the old behavior was intended.
  print(np.where("e"))


#Sort array (ascending array!)

In [6]:
z=np.array([1,5,3,9,7,4,0,7,6,3,8])
print("sorted array:-",np.sort(z))
print("sorted array:-",z )

sorted array:- [0 1 3 3 4 5 6 7 7 8 9]
sorted array:- [1 5 3 9 7 4 0 7 6 3 8]


#FOR alphabatics ascen order

In [15]:
al=np.array(['e','f','h','k','a','s','e'])     #can sorted 2d array
print(np.sort(al))

['a' 'e' 'e' 'f' 'h' 'k' 's']


#FILTER FUNCTION :- for getting a perticular element in array ex:-


In [17]:
er=np.array([1,"b",3,7,"m",9])
tf=[False,True,False,False,True,True]    #NOTE:- True or False is correct not lower case(true and false)
print(er[tf])

['b' 'm' '9']


In [14]:
#Descending order:-
len(z)
for i in range(11,0):
 x=[]
b=x.append(i)
print(b)


NameError: name 'x' is not defined

#Suffel Elements randomly in array

In [34]:
su=np.array([1,2,3,4,56,7,8,4,5,6,7,89,9])
#print("suffel data:-",np.random.shuffle(su))   #not correct formate!
#su2=np.random.shuffle(su)
np.random.shuffle(su)     #Only correct that format olny!
print("suffel data:-",su)   #Random show element in array!



suffel data:- [ 5  7 56  9  2  7  6  8  3 89  4  4  1]


In [45]:
su3=np.array([1,23,3,4,3,5,66,7,4,9,2,1,])   #reapitive elements show only one time! show all data in array format!
print("unique data:-",np.unique(su3))
un=np.unique(su3,return_index=True,return_counts=True)   #Case sensitive writting letters 
#print("unique data2:-",un,"Index no.:-",return_index=True,return_Counts=True)  #incorrect method!
print("unique data:-",un)

unique data:- [ 1  2  3  4  5  7  9 23 66]
unique data:- (array([ 1,  2,  3,  4,  5,  7,  9, 23, 66]), array([ 0, 10,  2,  3,  5,  7,  9,  1,  6], dtype=int64), array([2, 1, 2, 2, 1, 1, 1, 1, 1], dtype=int64))


#REsize funct (no. of rows,no. of element in each elements)


In [50]:
len(su3)
print('resize elements:-',np.resize(su3,(3,4)))
print('2nd 2d array element:------>' )
print("resize element2:-",np.resize(su3,(2,6)))


resize elements:- [[ 1 23  3  4]
 [ 3  5 66  7]
 [ 4  9  2  1]]
2nd 2d array element:------>
resize element2:- [[ 1 23  3  4  3  5]
 [66  7  4  9  2  1]]


#Inser date in numpy array

In [75]:
i=np.array([1,2,3,66,5])      #(varible,index,value insert)
f=np.insert(i,2,99)
print('inserted data:-',f)
print( )
print('insert data2:-',np.insert(i,4,77))   #Data only insert as integers not float no  naerst lower no.
print(  )
print('Data insert into many place(index):-',np.insert(i,(2,3,4),999)) 
l=np.array(['g','m','l'])
print(np.insert(l,(0,2,3),"x"))   #Can insert letters 
print()
print("string insert:-",np.insert(l,(2,3),("name",'sahu')))   #only insert first letter not insert complete name! at diff index and diff name!
print(  )
#i dont understand why am i not understanding data array strinf letter is not insert!  
n=np.array([[1,2,3],[4,5,6]])
print(np.insert(n,2,(66,66,66),axis=0))    
print(np.insert(n,2,0,axis=1))
print()
print(np.insert(n,2,786,axis=0))   #Along row inster elements!

inserted data:- [ 1  2 99  3 66  5]

insert data2:- [ 1  2  3 66 77  5]

Data insert into many place(index):- [  1   2 999   3 999  66 999   5]
['x' 'g' 'm' 'x' 'l' 'x']

string insert:- ['g' 'm' 'n' 'l' 's']

[[ 1  2  3]
 [ 4  5  6]
 [66 66 66]]
[[1 2 0 3]
 [4 5 0 6]]

[[  1   2   3]
 [  4   5   6]
 [786 786 786]]


#delete an element  in array 

In [78]:
de=np.array([1,2,34,4,5])
print('orignal data :-', de)
print(  )
print('delete data array:-',np.delete(de,2))   #Pass index no! to remove any value


orignal data :- [ 1  2 34  4  5]

delete data array:- [1 2 4 5]


In [79]:
z=np.matrix([[1,2],[1,2]])
y=np.matrix([[1,2],[1,2]])
print("multipplication of matrix:-",z.dot(y))

multipplication of matrix:- [[3 6]
 [3 6]]


#letse heckinhg code 

In [28]:
g=np.seed(5)
np.random.randint(1,6,4)
print(g)

AttributeError: module 'numpy' has no attribute 'seed'

In [27]:
sd=np.array([[[1,2,7],[2,3,9]]])
print("orignal array:-",sd)

print(   )
for k in sd.flat:
 print("1nd scilicing:-",k)
print(   )
for i in np.nditer(sd):
    print("2nd scilicing:-",i)
    

orignal array:- [[[1 2 7]
  [2 3 9]]]

1nd scilicing:- 1
1nd scilicing:- 2
1nd scilicing:- 7
1nd scilicing:- 2
1nd scilicing:- 3
1nd scilicing:- 9

2nd scilicing:- 1
2nd scilicing:- 2
2nd scilicing:- 7
2nd scilicing:- 2
2nd scilicing:- 3
2nd scilicing:- 9
