Array

In [ ]:
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr)                     #Both mwthod will same 
print(np.array([1,2,3,4,5]))

[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
g=np.array([[1,2,3,4]])   #2D array
print(g,g.ndim)       #ndim tell us dimention of array by sq brackets 


[[1 2 3 4]] 2


Airect method for creating array

In [ ]:
arr2=np.array([[[1,32,3,4,]]])    #3D array
print(arr2,arr2.ndim)

[[[ 1 32  3  4]]] 3


In [ ]:
arr2 =np.array([[[1,2,3],[4,5,6]]])
print(arr2,arr2.ndim)

[[[1 2 3]
  [4 5 6]]] 3


Differnt ways to creat numpy 

In [ ]:
#zeros elements in numpy
arr3=np.zeros(3)
print(arr3)

[0. 0. 0.]


In [ ]:
#zeros elements in numpy
arr3=np.zeros((3,4))  #learn terika of bracket!
print(arr3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr4=np.ones(3)
print(arr4 , arr4.ndim)

[1. 1. 1.] 1


In [ ]:
print(np.ones((3,4)))    #make all types of array 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
arr5=[]
print(np.empty(arr5))

1.0


In [ ]:
print(np.empty(3))

[1. 1. 1.]


In [ ]:
print(np.empty((2,3)))

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [4.22792893e-307 3.33772113e-307 1.05699581e-307]]


In [ ]:
ar=np.arange(5)
print(ar)

[0 1 2 3 4]


In [ ]:
print(np.arange(2,3))   form    #2(include) to 3 

[2]


In [ ]:
print(np.arange(1,7))   #fron 2 include to 7not includ 

[1 2 3 4 5 6]


In [ ]:
print(np.eye(3))    #for dioagonal element

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print(np.eye(2,4
            ))      #make any types of array

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [ ]:
print(np.linspace(1,4))    #creat array according to your choice how many you need element in same gap:---> (start,end,gap)

[1.         1.06122449 1.12244898 1.18367347 1.24489796 1.30612245
 1.36734694 1.42857143 1.48979592 1.55102041 1.6122449  1.67346939
 1.73469388 1.79591837 1.85714286 1.91836735 1.97959184 2.04081633
 2.10204082 2.16326531 2.2244898  2.28571429 2.34693878 2.40816327
 2.46938776 2.53061224 2.59183673 2.65306122 2.71428571 2.7755102
 2.83673469 2.89795918 2.95918367 3.02040816 3.08163265 3.14285714
 3.20408163 3.26530612 3.32653061 3.3877551  3.44897959 3.51020408
 3.57142857 3.63265306 3.69387755 3.75510204 3.81632653 3.87755102
 3.93877551 4.        ]


In [ ]:
print(np.linspace(2,16,6))     #(start,end,gap)   note :-->show bothelement -ve or may be +ve elements  

[ 2.   4.8  7.6 10.4 13.2 16. ]


In [ ]:
print(np.linspace(-4,4,8))

[-4.         -2.85714286 -1.71428571 -0.57142857  0.57142857  1.71428571
  2.85714286  4.        ]


In [ ]:
#rand  or randf values give (0 to 1),show always =ve values 
print(np.random.rand(3))

[0.59552186 0.5746387  0.36932016]


In [ ]:
print(np.random.rand(8))


[0.67438669 0.61895027 0.44823313 0.91849184 0.0126672  0.5371289
 0.34507585 0.53392736]


In [ ]:
er=np.random.rand(4)    #same method as example
print(er)


[0.2431834  0.32496355 0.24981846 0.37835065]


In [ ]:
print(np.rand(2,3))   #without .random get error

AttributeError: module 'numpy' has no attribute 'rand'

In [ ]:
print(np.random.randn(3))    #value 0 to 1 bw [0,1)  may be +ve or -ve vales 

[1.33368411 1.10645187 0.42637307]


In [ ]:
h=np.random.ranf(1)       #give elements btw [0 to 1)
print(h)

[0.92507698]


In [ ]:
         #thprs an error 
print(np.random.ranf(2,3))    #only takes one positional  elemants not 2 position elements!

TypeError: random_sample() takes at most 1 positional argument (2 given)

#Randit

In [ ]:
print(np.random.randint(2,10,5))       #randint  not randit×    #Elements may or may not be reapeted and same more time 

[3 3 6 9 4]


In [ ]:
print(np.random.randint(1,10,5))        #positional elements must 3 [start,end,no of elements)  imp NOTE:-

[9 2 3 8 7]


In [ ]:
print(np.random.randint(0,0.1,5))        #range decide according to your choice and no of elemets:-

ValueError: high <= 0

In [ ]:
print(np.random.randint(1,3,6))

[2 2 2 1 2 1]


In [ ]:
print(np.random.randint(2,3,5))        # all same and reapeated elem

[2 2 2 2 2]


#Data types 

In [ ]:
b=np.random.randint(2,7,4)          #.dtype
print(b,"dat types :-",b.dtype)    

[6 5 2 5] dat types :- int32


In [ ]:
b=np.array(["e","r","G","Y"])          #.dtype
print(b,"data types :-",b.dtype)      #string represent as ,U1

['e' 'r' 'G' 'Y'] data types :- <U1


In [ ]:
f=np.array([d,f,y,r,h])       #throw an error without double cout
print(f,"data types :-", f.dtype)

NameError: name 'd' is not defined

#convert  data types!

In [ ]:
d=np.array([1,2,3,"E","f","j"])      #combination of letters and integers is <U11
print(d,"data type",d.dtype)

['1' '2' '3' 'E' 'f' 'j'] data type <U11


In [ ]:
p=np.array([1,2,3,4])     #data convert into float 32bits
x=np.float32(p)
print(x)

[1. 2. 3. 4.]


In [ ]:
z=np.array([1,2,3,4])
print(z)
print("convert datatye is float :- ")
j=z.astype(float)
print(j)

[1 2 3 4]
convert datatye is float :- 
[1. 2. 3. 4.]
